In [2]:
#DATASET LINK: https://www.kaggle.com/datasets/mexwell/ransomware-dataset-2024

In [3]:
import warnings
from sklearn.exceptions import ConvergenceWarning

warnings.filterwarnings("ignore", category=ConvergenceWarning)

In [4]:
import pandas as pd

**T1: Load Data**

In [5]:
df = pd.read_csv('ransom.csv')

In [6]:
print(len(df))

21752

In [7]:
df.head()

,md5,sha1,file_extension,EntryPoint,PEType,MachineType,magic_number,bytes_on_last_page,pages_in_file,relocations,...,total_procsses,files_malicious,files_suspicious,files_text,files_unknown,dlls_calls,apis,Class,Category,Family
0,d5aa2b2506dd71b65307bb551a6a099d,62f4d55a1bb8396e493d7815dc44febed7161535,exe,0x108ec,PE32+,AMD AMD64,MZ,0x0090,0x0003,0x0000,...,0.0,0.0,0.0,0.0,0.0,6.0,162.0,Benign,Benign,Benign
1,8d1178cec97f96a9ede3efe2f30ef30e,ca40945a4e35d48794a5e13aacf16b8ae1caddeb,exe,0x25cf9c,PE32+,AMD AMD64,MZ,0x0090,0x0003,0x0000,...,93.0,0.0,0.0,0.0,0.0,22.0,778.0,Benign,Benign,Benign
2,c08d7afb7966f452cf5aa9283fe8880a,6f47b50480bea61ae4dfb75c12582990cc5ce770,exe,0x2a7e,PE32,"Intel 386 or later, and compatibles",MZ,0x0090,0x0003,0x0000,...,35.0,0.0,0.0,0.0,0.0,1.0,1.0,Benign,Benign,Benign
3,3554a3a99e7ffb57552aedcb2520f1d2,8c3d5b506a8d55f42f4c83ead3e4341255d1acfc,exe,0x64ca0,PE32+,AMD AMD64,MZ,0x0090,0x0003,0x0004,...,0.0,0.0,0.0,0.0,0.0,1.0,40.0,Benign,Benign,Benign
4,5be9511d42136df49d9501680e84109f,0a7d0c68c591db2f197b2169d226bebe6e9bdabe,exe,0x1b9ae,PE32,"Intel 386 or later, and compatibles",MZ,0x0090,0x0003,0x0000,...,36.0,0.0,0.0,0.0,0.0,1.0,1.0,Benign,Benign,Benign

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21752 entries, 0 to 21751
Data columns (total 77 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   md5                         21752 non-null  object
 1   sha1                        21752 non-null  object
 2   file_extension              21752 non-null  object
 3   EntryPoint                  21752 non-null  object
 4   PEType                      21752 non-null  object
 5   MachineType                 21752 non-null  object
 6   magic_number                21752 non-null  object
 7   bytes_on_last_page          21752 non-null  object
 8   pages_in_file               21752 non-null  object
 9   relocations                 21752 non-null  object
 10  size_of_header              21752 non-null  object
 11  min_extra_paragraphs        21752 non-null  object
 12  max_extra_paragraphs        21752 non-null  object
 13  init_ss_value               21752 non-null  object
 14  init_sp_value               21752 non-null  object
 15  init_ip_value               21752 non-null  object
 16  init_cs_value               21752 non-null  object
 17  over_lay_number             21752 non-null  object
 18  oem_identifier              21752 non-null  object
 19  address_of_ne_header        21752 non-null  object
 20  Magic                       21752 non-null  object
 21  SizeOfCode                  21752 non-null  object
 22  SizeOfInitializedData       21752 non-null  object
 23  SizeOfUninitializedData     21752 non-null  object
 24  AddressOfEntryPoint         21752 non-null  object
 25  BaseOfCode                  21752 non-null  object
 26  BaseOfData                  21752 non-null  object
 27  ImageBase                   21752 non-null  object
 28  SectionAlignment            21752 non-null  object
 29  FileAlignment               21752 non-null  object
 30  OperatingSystemVersion      21752 non-null  object
 31  ImageVersion                21752 non-null  object
 32  SizeOfImage                 21752 non-null  object
 33  SizeOfHeaders               21752 non-null  object
 34  Checksum                    21752 non-null  object
 35  Subsystem                   21752 non-null  object
 36  DllCharacteristics          21752 non-null  object
 37  SizeofStackReserve          21752 non-null  object
 38  SizeofStackCommit           21752 non-null  object
 39  SizeofHeapCommit            21752 non-null  object
 40  SizeofHeapReserve           21752 non-null  object
 41  LoaderFlags                 21752 non-null  object
 42  text_VirtualSize            21752 non-null  object
 43  text_VirtualAddress         21752 non-null  object
 44  text_SizeOfRawData          21752 non-null  object
 45  text_PointerToRawData       21752 non-null  object
 46  text_PointerToRelocations   21752 non-null  object
 47  text_PointerToLineNumbers   21752 non-null  object
 48  text_Characteristics        21752 non-null  object
 49  rdata_VirtualSize           21752 non-null  object
 50  rdata_VirtualAddress        21752 non-null  object
 51  rdata_SizeOfRawData         21752 non-null  object
 52  rdata_PointerToRawData      21752 non-null  object
 53  rdata_PointerToRelocations  21752 non-null  object
 54  rdata_PointerToLineNumbers  21752 non-null  object
 55  rdata_Characteristics       21752 non-null  object
 56  registry_read               21752 non-null  float64
 57  registry_write              21752 non-null  float64
 58  registry_delete             21752 non-null  float64
 59  registry_total              21752 non-null  float64
 60  network_threats             21752 non-null  float64
 61  network_dns                 21752 non-null  float64
 62  network_http                21752 non-null  float64
 63  network_connections         21752 non-null  float64
 64  processes_malicious         21752 non-null  float64
 65  processes_suspicious        21752 non-null  float64
 66  processes_monitored         21752 non-null  float64
 67  total_procsses              21752 non-null  float64
 68  files_malicious             21752 non-null  float64
 69  files_suspicious            21752 non-null  float64
 70  files_text                  21752 non-null  float64
 71  files_unknown               21752 non-null  float64
 72  dlls_calls                  21752 non-null  float64
 73  apis                        21752 non-null  float64
 74  Class                       21752 non-null  object
 75  Category                    21752 non-null  object
 76  Family                      21752 non-null  object
dtypes: float64(18), object(59)
memory usage: 12.8+ MB

In [9]:
df = df[df["Category"].str.lower().isin(["benign", "ransomware"])]

benign = df[df["Category"].str.lower() == "benign"]
ransom = df[df["Category"].str.lower() == "ransomware"]

print("benign rows:", len(benign))
print("ransomware rows:", len(ransom))

benign rows: 10876
ransomware rows: 4762

**T2: Process Data**

In [10]:
benign = df[df["Category"] == "Benign"]
ransom = df[df["Category"] == "Ransomware"]

print(len(benign), len(ransom))


benign_sampled = benign.sample(n=5000, random_state=42)


df_balanced = pd.concat([benign_sampled, ransom], axis=0)


df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)


df_balanced.to_csv("ransom_balanced.csv", index=False)

10876 4762

In [11]:
df = pd.read_csv('ransom_balanced.csv')

In [12]:
for col in df.columns:
    print(col, "=>", df[col].nunique())

md5 => 5208
sha1 => 5262
file_extension => 1
EntryPoint => 3454
PEType => 3
MachineType => 3
magic_number => 1
bytes_on_last_page => 50
pages_in_file => 45
relocations => 36
size_of_header => 32
min_extra_paragraphs => 39
max_extra_paragraphs => 33
init_ss_value => 31
init_sp_value => 35
init_ip_value => 41
init_cs_value => 38
over_lay_number => 42
oem_identifier => 39
address_of_ne_header => 47
Magic => 2
SizeOfCode => 1744
SizeOfInitializedData => 1586
SizeOfUninitializedData => 266
AddressOfEntryPoint => 3474
BaseOfCode => 225
BaseOfData => 706
ImageBase => 63
SectionAlignment => 8
FileAlignment => 6
OperatingSystemVersion => 19
ImageVersion => 64
SizeOfImage => 1410
SizeOfHeaders => 20
Checksum => 1949
Subsystem => 4
DllCharacteristics => 45
SizeofStackReserve => 48
SizeofStackCommit => 30
SizeofHeapCommit => 8
SizeofHeapReserve => 19
LoaderFlags => 4
text_VirtualSize => 3440
text_VirtualAddress => 87
text_SizeOfRawData => 1541
text_PointerToRawData => 103
text_PointerToRelocations => 6
text_PointerToLineNumbers => 12
text_Characteristics => 24
rdata_VirtualSize => 2281
rdata_VirtualAddress => 623
rdata_SizeOfRawData => 768
rdata_PointerToRawData => 1235
rdata_PointerToRelocations => 3
rdata_PointerToLineNumbers => 3
rdata_Characteristics => 24
registry_read => 2754
registry_write => 307
registry_delete => 99
registry_total => 2825
network_threats => 1
network_dns => 188
network_http => 77
network_connections => 247
processes_malicious => 41
processes_suspicious => 24
processes_monitored => 137
total_procsses => 204
files_malicious => 282
files_suspicious => 2009
files_text => 988
files_unknown => 621
dlls_calls => 49
apis => 571
Class => 2
Category => 2
Family => 13

In [13]:
print(len(df))

9762

In [14]:
df = df.drop(columns=["sha1", "Family", "Class", "magic_number","md5", "network_threats", "file_extension"], inplace=False)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9762 entries, 0 to 9761
Data columns (total 70 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   EntryPoint                  9762 non-null   object
 1   PEType                      9762 non-null   object
 2   MachineType                 9762 non-null   object
 3   bytes_on_last_page          9762 non-null   object
 4   pages_in_file               9762 non-null   object
 5   relocations                 9762 non-null   object
 6   size_of_header              9762 non-null   object
 7   min_extra_paragraphs        9762 non-null   object
 8   max_extra_paragraphs        9762 non-null   object
 9   init_ss_value               9762 non-null   object
 10  init_sp_value               9762 non-null   object
 11  init_ip_value               9762 non-null   object
 12  init_cs_value               9762 non-null   object
 13  over_lay_number             9762 non-null   object
 14  oem_identifier              9762 non-null   object
 15  address_of_ne_header        9762 non-null   object
 16  Magic                       9762 non-null   object
 17  SizeOfCode                  9762 non-null   object
 18  SizeOfInitializedData       9762 non-null   object
 19  SizeOfUninitializedData     9762 non-null   object
 20  AddressOfEntryPoint         9762 non-null   object
 21  BaseOfCode                  9762 non-null   object
 22  BaseOfData                  9762 non-null   object
 23  ImageBase                   9762 non-null   object
 24  SectionAlignment            9762 non-null   object
 25  FileAlignment               9762 non-null   object
 26  OperatingSystemVersion      9762 non-null   object
 27  ImageVersion                9762 non-null   object
 28  SizeOfImage                 9762 non-null   object
 29  SizeOfHeaders               9762 non-null   object
 30  Checksum                    9762 non-null   object
 31  Subsystem                   9762 non-null   object
 32  DllCharacteristics          9762 non-null   object
 33  SizeofStackReserve          9762 non-null   object
 34  SizeofStackCommit           9762 non-null   object
 35  SizeofHeapCommit            9762 non-null   object
 36  SizeofHeapReserve           9762 non-null   object
 37  LoaderFlags                 9762 non-null   object
 38  text_VirtualSize            9762 non-null   object
 39  text_VirtualAddress         9762 non-null   object
 40  text_SizeOfRawData          9762 non-null   object
 41  text_PointerToRawData       9762 non-null   object
 42  text_PointerToRelocations   9762 non-null   object
 43  text_PointerToLineNumbers   9762 non-null   object
 44  text_Characteristics        9762 non-null   object
 45  rdata_VirtualSize           9762 non-null   object
 46  rdata_VirtualAddress        9762 non-null   object
 47  rdata_SizeOfRawData         9762 non-null   object
 48  rdata_PointerToRawData      9762 non-null   object
 49  rdata_PointerToRelocations  9762 non-null   object
 50  rdata_PointerToLineNumbers  9762 non-null   object
 51  rdata_Characteristics       9762 non-null   object
 52  registry_read               9762 non-null   float64
 53  registry_write              9762 non-null   float64
 54  registry_delete             9762 non-null   float64
 55  registry_total              9762 non-null   float64
 56  network_dns                 9762 non-null   float64
 57  network_http                9762 non-null   float64
 58  network_connections         9762 non-null   float64
 59  processes_malicious         9762 non-null   float64
 60  processes_suspicious        9762 non-null   float64
 61  processes_monitored         9762 non-null   float64
 62  total_procsses              9762 non-null   float64
 63  files_malicious             9762 non-null   float64
 64  files_suspicious            9762 non-null   float64
 65  files_text                  9762 non-null   float64
 66  files_unknown               9762 non-null   float64
 67  dlls_calls                  9762 non-null   float64
 68  apis                        9762 non-null   float64
 69  Category                    9762 non-null   object
dtypes: float64(17), object(53)
memory usage: 5.2+ MB

In [16]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [17]:
cats = df.select_dtypes(include='object').columns
nums = df.select_dtypes(include='float64').columns

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(drop = "if_binary",handle_unknown='ignore', sparse_output=False), cats),
        ('num', StandardScaler(), nums)
    ], remainder='drop')

In [18]:
data_processed = preprocessor.fit_transform(df)
encoded_columns = preprocessor.transformers_[0][1].get_feature_names_out(cats)
scaled_columns = preprocessor.transformers_[1][2]
all_columns = list(encoded_columns) + list(scaled_columns)

In [19]:
data_final= pd.DataFrame(data_processed, columns=all_columns)
data_final.head()

,EntryPoint_0x0000,EntryPoint_0x0154,EntryPoint_0x0208,EntryPoint_0x0240,EntryPoint_0x0a8a,EntryPoint_0x0efa,EntryPoint_0x1000,EntryPoint_0x10000,EntryPoint_0x1001b,EntryPoint_0x1002c0,...,processes_malicious,processes_suspicious,processes_monitored,total_procsses,files_malicious,files_suspicious,files_text,files_unknown,dlls_calls,apis
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.201920,0.361912,0.092324,0.095096,0.405924,-0.058613,-0.060190,0.493349,-0.539198,-0.085632
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.124428,-0.266174,0.991822,0.894336,-0.236582,-0.184552,0.375087,-0.115321,-0.362155,0.093874
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.528269,-0.266174,-0.301206,-0.918574,-0.236582,-0.273961,-0.283363,-0.190280,3.001652,3.568584
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.528269,-0.266174,-0.188769,-0.372752,-0.236582,-0.272918,-0.283363,-0.190280,-0.716240,-0.515162
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-0.528269,-0.266174,-0.273097,-0.236296,-0.236582,-0.273961,-0.283363,-0.190280,0.877142,2.792864

In [20]:
display(data_final['Category_Ransomware'].value_counts())

Category_Ransomware
0.0    5000
1.0    4762
Name: count, dtype: int64

**T3: Partition Data**

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_data= data_final.drop(columns=['Category_Ransomware'])
y_lable= data_final['Category_Ransomware']

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X_data, y_lable, test_size=0.3, random_state=42, stratify=y_lable, shuffle=True)

In [24]:
print(f"training data:{X_train.shape}, test data:{X_test.shape}")

training data:(6833, 25834), test data:(2929, 25834)

In [25]:
display(y_train.value_counts())
display(y_test.value_counts())

Category_Ransomware
0.0    3500
1.0    3333
Name: count, dtype: int64

Category_Ransomware
0.0    1500
1.0    1429
Name: count, dtype: int64

**T4: Create Models**

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform

In [27]:
lg = LogisticRegression()

lg_params = {
    'C': uniform(0.01, 10),
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear','lbfgs']
}

In [28]:
lg_search = RandomizedSearchCV(lg, lg_params,
                              n_iter=10, cv=5, random_state=42,
                              scoring='balanced_accuracy',n_jobs=-1)

lg_search.fit(X_train, y_train)

In [ ]:
lg_search.best_score_

np.float64(0.9970851884225198)

In [ ]:
lg_fitted= lg_search.best_estimator_
print(lg_fitted)

LogisticRegression(C=np.float64(7.3299394181140505), penalty='l1',
                   solver='liblinear')

**T5 Evaluate Models**

In [ ]:
lg_y_pred_test =  lg_fitted.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
def cm(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()

    print("Confusion Matrix (rows = true, columns = predicted)")
    print("            Pred 0 (Benign)   Pred 1 (Ransomware)")
    print(f"True 0  (Benign)    TN = {tn}          FP = {fp}")
    print(f"True 1  (Ransom)    FN = {fn}          TP = {tp}")
    print()
    print(f"TN = {tn}, FP = {fp}, FN = {fn}, TP = {tp}")

In [ ]:
eval_test=[]

def evaluate(y_test,y_test_pred):
  accuracy_test=accuracy_score(y_test,y_test_pred)

  bal_accuracy_test=balanced_accuracy_score(y_test,y_test_pred)

  precision_test=precision_score(y_test,y_test_pred)

  recall_test=recall_score(y_test,y_test_pred)

  f1_test=f1_score(y_test,y_test_pred)

  eval_test.append({"accuracy": accuracy_test, "balanced acc": bal_accuracy_test,\
                    "precision": precision_test, "recall": recall_test,
                    "f1": f1_test
                    })

In [ ]:
evaluate(y_test,lg_y_pred_test)

In [ ]:
test_eval_all=pd.DataFrame(eval_test,index=['lg'])

In [ ]:
test_eval_all

    accuracy  balanced acc  precision    recall        f1
lg  0.996586        0.9966   0.995807  0.997201  0.997201

In [ ]:
cm(y_test, lg_y_pred_test)

Confusion Matrix (rows = true, columns = predicted)
            Pred 0 (Benign)   Pred 1 (Ransomware)
True 0  (Benign)    TN = 1494          FP = 6
True 1  (Ransom)    FN = 4          TP = 1425

TN = 1494, FP = 6, FN = 4, TP = 1425